services:
  cfchem_db: # note: having the DB as part of the compose file is not strictly necessary if we already have the DB installed on our system - but since the cfchemdb is so small (<1GB) it's not a major concern
    image: unmtransinfo/cfchemdb_db
  cfchem_api:
    build:
      context: ./app
    depends_on:
      - cfchem_db
    env_file:
      - .env
    networks:
      - cfchem_net
  cfchem_ui:
    build:
      context: https://github.com/unmtransinfo/CFChemUI.git#main
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npx vite build
    volumes:
      - static_files_cfchem:/app/dist/
    env_file:
      - .env
    networks:
      - cfchem_net
  nginx:
    image: nginx:1
    volumes:
      - static_files_cfchem:/usr/share/nginx/html/static_files_cfchem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx:/etc/nginx #used for nginx configuration scanning with yandex/gixy
    ports:
      - ${CFCHEM_NGINX_SSL_PORT:-443}:443
      - ${CFCHEM_NGINX_HTTP_PORT:-80}:80
    depends_on:
      cfchem_api:
        condition: service_started
      cfchem_ui:
        condition: service_started
    networks:
      - cfchem_net

volumes:
  nginx:
  static_files_cfchem:

networks:
  cfchem_net: