services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
    env_file:
      - ./app/.env
