volumes:
  nginx:
  static_files_cfchem:
services:
  cfchem_api:
    build:
      context: ./app
    depends_on:
      - mysql
    env_file:
      - .env
  cfchem_ui:
    build:
      context: https://github.com/unmtransinfo/CFChemUI.git#main
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    command: su -c "npm i && npm run build"
    volumes:
      - static_files_cfchem:/app/dist/
    env_file:
      - .env
  nginx:
    image: nginx:1
    volumes:
      - static_files_cfchem:/usr/share/nginx/html/static_files_cfchem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx:/etc/nginx #used for nginx configuration scanning with yandex/gixy
    ports:
      - ${CFCHEM_NGINX_SSL_PORT:-443}:443
      - ${CFCHEM_NGINX_HTTP_PORT:-80}:80
    depends_on:
      cfchem_api:
        condition: service_started
      cfchem_ui:
        condition: service_started
  mysql:
    image: unmtransinfo/cfchemdb_db